import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';

export default function Trial() {
  const navigate = useNavigate();
  const [githubUrl, setGithubUrl] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReadme, setGeneratedReadme] = useState('');
  const [trialUsed, setTrialUsed] = useState(false);

  // Check if trial has been used on component mount
  useEffect(() => {
    const hasUsedTrial = localStorage.getItem('reporead_trial_used');
    if (hasUsedTrial === 'true') {
      setTrialUsed(true);
    }
  }, []);

  const handleGenerate = async () => {
    if (!githubUrl.trim()) return;
    
    setIsGenerating(true);
    
    // Simulate API call with loading state
    setTimeout(() => {
      // Mock generated README
      const mockReadme = `# ${githubUrl.split('/').pop() || 'Repository'}

## 📋 Overview
This is an automatically generated README for your repository. Bob has analyzed your code structure and created comprehensive documentation.

## ✨ Features
- Feature detection from code analysis
- Automatic dependency identification
- Smart documentation generation
- Code structure visualization

## 🚀 Installation

\`\`\`bash
# Clone the repository
git clone ${githubUrl}

# Navigate to project directory
cd ${githubUrl.split('/').pop()}

# Install dependencies
npm install
\`\`\`

## 💻 Usage

\`\`\`javascript
// Example usage
const app = require('./app');

app.start();
\`\`\`

## 🛠️ Technologies Used
- Node.js
- Express
- React
- MongoDB

## 📦 Project Structure
\`\`\`
project/
├── src/
│   ├── components/
│   ├── pages/
│   └── utils/
├── public/
├── package.json
└── README.md
\`\`\`

## 🤝 Contributing
Contributions are welcome! Please feel free to submit a Pull Request.

## 📄 License
This project is licensed under the MIT License.

## 👤 Author
Generated with ❤️ by RepoRead

---
*This README was automatically generated by Bob*`;

      setGeneratedReadme(mockReadme);
      setIsGenerating(false);
      
      // Mark trial as used
      localStorage.setItem('reporead_trial_used', 'true');
      setTrialUsed(true);
    }, 2500);
  };

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      {/* Navbar */}
      <nav className="border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex-shrink-0">
              <Link to="/" className="text-2xl font-bold text-white">
                RepoRead
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">See it in Action</h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Paste your GitHub repository URL and watch Bob generate your README instantly. 
            One free trial, no account needed.
          </p>
        </div>

        {/* Trial Already Used State */}
        {trialUsed && !generatedReadme ? (
          <div className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-12 text-center">
            <div className="mb-6">
              <svg className="w-20 h-20 mx-auto text-gray-600 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
              <h2 className="text-2xl font-bold mb-3">You've used your free trial</h2>
              <p className="text-gray-400 mb-8">
                Create an account to continue generating READMEs.
              </p>
            </div>
            <button
              onClick={() => navigate('/register')}
              className="bg-[#F7604D] hover:bg-[#d94d3a] text-white font-semibold py-3 px-8 rounded-lg transition-colors"
            >
              Create Account
            </button>
          </div>
        ) : (
          <>
            {/* Input Section */}
            {!generatedReadme && (
              <div className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-8 mb-8">
                <div className="space-y-4">
                  <label htmlFor="github-url" className="block text-sm font-medium text-gray-300">
                    GitHub Repository URL
                  </label>
                  <input
                    id="github-url"
                    type="text"
                    value={githubUrl}
                    onChange={(e) => setGithubUrl(e.target.value)}
                    placeholder="https://github.com/username/repo"
                    disabled={isGenerating}
                    className="w-full px-4 py-3 bg-[#0a0a0a] border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#F7604D] focus:border-transparent disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  
                  <button
                    onClick={handleGenerate}
                    disabled={isGenerating || !githubUrl.trim()}
                    className="w-full bg-[#F7604D] hover:bg-[#d94d3a] disabled:bg-gray-700 disabled:cursor-not-allowed text-white font-semibold py-3 px-6 rounded-lg transition-colors"
                  >
                    {isGenerating ? 'Bob is reading your repo...' : 'Generate README'}
                  </button>
                </div>
              </div>
            )}

            {/* Loading State */}
            {isGenerating && (
              <div className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-12 text-center">
                <div className="flex flex-col items-center">
                  <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-[#F7604D] mb-4"></div>
                  <p className="text-xl text-gray-300">Bob is reading your repo...</p>
                  <p className="text-sm text-gray-500 mt-2">Analyzing code structure and generating documentation</p>
                </div>
              </div>
            )}

            {/* Generated README Display */}
            {generatedReadme && (
              <>
                <div className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-6 mb-8">
                  <div className="flex justify-between items-center mb-4">
                    <h2 className="text-2xl font-bold">Generated README</h2>
                  </div>
                  <div className="bg-[#0a0a0a] border border-gray-700 rounded-lg p-6 max-h-[500px] overflow-y-auto">
                    <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono">
                      {generatedReadme}
                    </pre>
                  </div>
                </div>

                {/* Call to Action Banner */}
                <div className="relative bg-gradient-to-r from-[#1a1a1a] to-[#2a1a1a] border-2 border-[#F7604D] rounded-lg p-8 overflow-hidden">
                  {/* Orange Glow Effect */}
                  <div className="absolute inset-0 bg-[#F7604D] opacity-5 blur-xl"></div>
                  
                  <div className="relative z-10 text-center">
                    <h3 className="text-2xl font-bold mb-3">Liked what you saw?</h3>
                    <p className="text-gray-300 mb-6">
                      Create a free account to unlock unlimited generations and save your READMEs.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                      <button
                        onClick={() => navigate('/register')}
                        className="bg-[#F7604D] hover:bg-[#d94d3a] text-white font-semibold py-3 px-8 rounded-lg transition-colors"
                      >
                        Create Account
                      </button>
                      <button
                        onClick={() => navigate('/login')}
                        className="bg-transparent border-2 border-[#F7604D] hover:bg-[#F7604D]/10 text-white font-semibold py-3 px-8 rounded-lg transition-colors"
                      >
                        Login
                      </button>
                    </div>
                  </div>
                </div>
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}

// Made with Bob